version: '3'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5050:5050'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
